
services:
  - type: web
    name: kampagnen-api
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "playwright install && uvicorn main:app --host 0.0.0.0 --port 10000"
    envVars: []
